version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules  
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start  

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: watchmedo auto-restart --patterns=*.py --recursive -- uvicorn app:app --host 0.0.0.0 --port 8000

  generator:
    build: ./generator
    volumes:
      - ./generator:/app
    command: watchmedo auto-restart --patterns=*.py --recursive -- python generate_sudoku.py
    depends_on:
      - db_sudoku

  db_sudoku:
    image: postgres
    environment:
      POSTGRES_USER: sudoku_user
      POSTGRES_PASSWORD: sudoku_pass
      POSTGRES_DB: sudoku_db
    volumes:
      - db_sudoku_data:/var/lib/postgresql/data
      - ./db_sudoku/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sudoku_user -d sudoku_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_sudoku_data:
